/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__drpc__stream_parser
#define __PYX_HAVE__drpc__stream_parser


#ifndef __PYX_HAVE_API__drpc__stream_parser

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(uint32_t) SEQ_MAX;

#endif /* !__PYX_HAVE_API__drpc__stream_parser */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initstream_parser(void);
#else
PyMODINIT_FUNC PyInit_stream_parser(void);
#endif

#endif /* !__PYX_HAVE__drpc__stream_parser */
